// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDiY315imf-oUTLiwgg9QP15Z0LDzmkdcI',
    appId: '1:473720583036:web:32f86cee4fb376dc9b6af9',
    messagingSenderId: '473720583036',
    projectId: 'my-pharmacy-856f8',
    authDomain: 'my-pharmacy-856f8.firebaseapp.com',
    storageBucket: 'my-pharmacy-856f8.appspot.com',
    measurementId: 'G-86XE16SLTB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCHAff3MUxsfKiYTOKPlL8vlm5vqpUDTAw',
    appId: '1:473720583036:android:4c2bbc1f4df51bc49b6af9',
    messagingSenderId: '473720583036',
    projectId: 'my-pharmacy-856f8',
    storageBucket: 'my-pharmacy-856f8.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCnrT4hCI_9oO8T4lVLMMvfIMf9CyHBKA0',
    appId: '1:473720583036:ios:522f1f49d1002dc39b6af9',
    messagingSenderId: '473720583036',
    projectId: 'my-pharmacy-856f8',
    storageBucket: 'my-pharmacy-856f8.appspot.com',
    iosBundleId: 'com.example.myPharmacy',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCnrT4hCI_9oO8T4lVLMMvfIMf9CyHBKA0',
    appId: '1:473720583036:ios:522f1f49d1002dc39b6af9',
    messagingSenderId: '473720583036',
    projectId: 'my-pharmacy-856f8',
    storageBucket: 'my-pharmacy-856f8.appspot.com',
    iosBundleId: 'com.example.myPharmacy',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDiY315imf-oUTLiwgg9QP15Z0LDzmkdcI',
    appId: '1:473720583036:web:0430ea402fb767bc9b6af9',
    messagingSenderId: '473720583036',
    projectId: 'my-pharmacy-856f8',
    authDomain: 'my-pharmacy-856f8.firebaseapp.com',
    storageBucket: 'my-pharmacy-856f8.appspot.com',
    measurementId: 'G-F8J87JFWK8',
  );
}
